---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create glance cache management cron jobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ 59 |random }}"
    day: "*"
    hour: "{{ item.hour }}"
    month: "*"
    state: present
    job: "{{ item.name }}"
    user: glance
  with_items:
    - name: glance-cache-pruner
      hour: "*"
    - name: glance-cache-cleaner
      hour: "{{ 23|random }}"
  when: glance_flavor | search("cache")
  tags:
    - glance-cron

- name: Drop Glance Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ glance_system_user_name }}"
    group: "{{ glance_system_group_name }}"
  with_items:
    - { src: "glance-api.conf.j2", dest: "/etc/glance/glance-api.conf" }
    - { src: "glance-cache.conf.j2", dest: "/etc/glance/glance-cache.conf" }
    - { src: "glance-registry.conf.j2", dest: "/etc/glance/glance-registry.conf" }
    - { src: "glance-scrubber.conf.j2", dest: "/etc/glance/glance-scrubber.conf" }
  notify:
    - Restart glance api
    - Restart glance registry
  tags:
    - glance-config

- name: Drop Glance Config(s)
  copy:
    src: "{{ item }}"
    dest: "/etc/glance/{{ item }}"
    owner: "{{ glance_system_user_name }}"
    group: "{{ glance_system_group_name }}"
  with_items:
    - glance-api-paste.ini
    - glance-registry-paste.ini
    - policy.json
    - schema.json
  notify:
    - Restart glance api
    - Restart glance registry
  tags:
    - glance-config
