---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

glance_main_group_name: glance_all

## System info
glance_system_user_name: glance
glance_system_group_name: glance
glance_system_shell: /bin/false
glance_system_comment: glance system user
glance_system_user_home: "/var/lib/{{ glance_system_user_name }}"

glance_flavor: "keystone+cachemanagement"
glance_registry_host: "{{ internal_lb_vip_address }}"
glance_notification_driver: noop
glance_rpc_backend: glance.openstack.common.rpc.impl_kombu
glance_default_store: file

## Swift Options
glance_swift_store_auth_address: NoAuthAddress
glance_swift_store_user: NoUser
glance_swift_store_key: NoKey
glance_swift_store_region: NoRegion
glance_swift_store_container: NoContainer
glance_swift_store_endpoint_type: internalURL

## DB info
glance_galera_database: glance
glance_galera_user: glance

glance_role_name: admin
glance_api_bind_address: 0.0.0.0
glance_api_service_port: 9292

glance_registry_bind_address: 0.0.0.0
glance_registry_service_port: 9191

## Service Type and Data
glance_service_region: RegionOne
glance_service_name: glance
glance_service_port: 9292
glance_service_proto: http
glance_service_type: image
glance_service_description: "Glance Image Service"
glance_service_user_name: glance
glance_service_tenant_name: service
glance_service_publicurl: "{{ glance_service_proto }}://{{ external_lb_vip_address }}:{{ glance_service_port }}"
glance_service_internalurl: "{{ glance_service_proto }}://{{ internal_lb_vip_address }}:{{ glance_service_port }}"
glance_service_adminurl: "{{ glance_service_proto }}://{{ internal_lb_vip_address }}:{{ glance_service_port }}"

## Git Source
glance_git_repo: https://github.com/openstack/glance
glance_git_install_branch: stable/juno
glance_git_repo_path: "glance_{{ glance_git_install_branch | replace('/', '_') }}"
glance_git_dest: "/opt/{{ glance_git_repo_path }}"

# Common apt packages
glance_apt_packages:
  - rsync
  - git

# Common pip packages
glance_pip_packages:
  - warlock
  - MySQL-python
  - python-memcached
  - pycrypto
  - python-glanceclient
  - python-swiftclient
  - python-cinderclient
  - python-keystoneclient
  - keystonemiddleware
