---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## System info
keystone_system_user_name: keystone
keystone_system_group_name: keystone
keystone_system_service_name: apache2
keystone_system_shell: /bin/false
keystone_system_comment: keystone system user

keystone_rpc_backend: rabbit

## Drivers
keystone_auth_methods: "password,token"
keystone_identity_driver: keystone.identity.backends.sql.Identity
keystone_token_provider: "keystone.token.providers.uuid.Provider"

keystone_bind_address: 0.0.0.0
keystone_verbose: True
keystone_debug: False

## DB info
keystone_galera_user: keystone
keystone_galera_database: keystone

## Role info
keystone_role_name: admin

## Admin info
keystone_admin_port: 35357
keystone_admin_user_name: admin
keystone_admin_tenant_name: admin
keystone_admin_description: Admin Tenant

## Service Type and Data
keystone_service_region: Region1
keystone_service_name: keystone
keystone_service_port: 5000
keystone_service_type: identity
keystone_service_description: "Keystone Identity Service"
keystone_service_user_name: keystone
keystone_service_tenant_name: service
keystone_service_publicurl: "http://{{ external_lb_vip_address }}:{{ keystone_service_port }}/v2.0"
keystone_service_internalurl: "http://{{ internal_lb_vip_address }}:{{ keystone_service_port }}/v2.0"
keystone_service_adminurl: "http://{{ internal_lb_vip_address }}:{{ keystone_admin_port }}/v2.0"

## Git Source
keystone_git_repo: https://github.com/openstack/keystone
keystone_git_install_branch: stable/juno
keystone_git_repo_path: "keystone_{{ keystone_git_install_branch | replace('/', '_') }}"
keystone_git_dest: "/opt/{{ keystone_git_repo_path }}"

## Apache setup
keystone_apache_log_level: info
keystone_apache_processes: 3
keystone_apache_threads: 10

keystone_ssl_enabled: false
keystone_ssl_cert: /etc/ssl/certs/apache.cert
keystone_ssl_key: /etc/ssl/private/apache.key
keystone_ssl_cert_path: /etc/ssl/certs

## Caching
# If set this will enable dog pile cache for keystone. 
# keystone_cache_backend_argument: url:127.0.0.1:11211

## LDAP section
# Define keystone ldap information here.
# See the http://docs.openstack.org/admin-guide-cloud/content/configuring-keystone-for-ldap-backend.html
# for more information on available options. The sections here are defined as key: value pairs. Each
# top level key bellow ``keystone_ldap`` is a section.
# (EXAMPLE LAYOUT)
# keystone_ldap:
#   ldap:
#     url: "ldap://127.0.0.1"
#     user: "root"
#     password: "secrete"
#     ...

# Common apt packages
keystone_apt_packages:
  - git
  - libsasl2-dev
  - debhelper
  - dh-apparmor
  - docutils-common
  - libjs-sphinxdoc
  - libjs-underscore 
  - libxslt1.1 
  - libldap2-dev
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi

# Common pip packages
keystone_pip_packages:
  - repoze.lru
  - pbr
  - MySQL-python
  - pycrypto
  - python-memcached
  - python-keystoneclient
  - keystonemiddleware
  - lxml
