---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## URL for the frozen rpc repo.
opc_repo_url: "http://mirror.rackspace.com/rackspaceprivatecloud"


## Release of the Rackspace Private Cloud
opc_release: master


## Verbosity Options
debug: False
verbose: True


## RabbitMQ
rabbitmq_userid: openstack
rabbitmq_cluster_name: rpc
rabbitmq_port: 5672
rabbitmq_servers: "{% for host in groups['rabbitmq_all'] %}{{ hostvars[host]['container_address'] }}:{{ rabbitmq_port }}{% if not loop.last %},{% endif %}{% endfor %}"


## Galera
galera_wsrep_cluster_address: "{% for host in groups['galera_all'] %}{{ hostvars[host]['container_address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
galera_wsrep_address: "{{ container_address }}"
galera_monitoring_user: haproxy
galera_root_user: root
# Set ``galera_max_connections`` to override the calculated max connections.
# galera_max_connections: 500


## Logstash
logstash_port: 5544


## Memcached options
memcached_listen: "{{ container_address }}"
base_memcached_memory: "{{ ansible_memtotal_mb | default(1537) | int / 2 }}"
memcached_memory: "{{ base_memcached_memory | int }}"
memcached_port: 11211
memcached_servers: "{% for host in groups['memcached'] %}{{ hostvars[host]['container_address'] }}:{{ memcached_port }}{% if not loop.last %},{% endif %}{% endfor %}"


## Nova
nova_service_port: 8774
nova_service_proto: http
nova_service_user_name: nova
nova_service_tenant_name: service
nova_service_adminuri: "{{ nova_service_proto }}://{{ internal_lb_vip_address }}:{{ nova_service_port }}"
nova_service_region: RegionOne


## Neutron
neutron_service_port: 9696
neutron_service_proto: http
neutron_service_user_name: neutron
neutron_service_tenant_name: service
neutron_service_adminuri: "{{ neutron_service_proto }}://{{ internal_lb_vip_address }}:{{ neutron_service_port }}"
neutron_service_region: RegionOne


## Glance
glance_service_port: 9292
glance_service_proto: http
glance_service_user_name: glance
glance_service_tenant_name: service
glance_service_adminurl: "{{ glance_service_proto }}://{{ internal_lb_vip_address }}:{{ glance_service_port }}"
glance_service_region: RegionOne
glance_api_servers: "{% for host in groups['glance_all'] %}{{ hostvars[host]['container_address'] }}:{{ glance_service_port }}{% if not loop.last %},{% endif %}{% endfor %}"


## Keystone
keystone_admin_port: 35357
keystone_service_port: 5000
keystone_service_proto: http
keystone_service_user_name: keystone
keystone_service_tenant_name: service
keystone_service_uri: "{{ keystone_service_proto }}://{{ internal_lb_vip_address }}"
keystone_service_adminuri: "{{ keystone_service_uri }}:{{ keystone_admin_port }}"
keystone_service_adminurl: "{{ keystone_service_adminuri }}/v2.0"
keystone_identity_uri: "{{ keystone_service_uri }}:{{ keystone_service_port }}"
keystone_cache_backend_argument: "url:{% for host in groups['memcached'] %}{{ hostvars[host]['container_address'] }}{% if not loop.last %},{% endif %}{% endfor %}:{{ memcached_port }}"
keystone_service_region: RegionOne


## Openstack Openrc 
openrc_os_auth_url: "{{ keystone_identity_uri }}/v2.0"
openrc_os_password: "{{ keystone_auth_admin_password }}"
